[32m2024-09-26 09:51:59 -0500[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - f5a914fa-3413-48d5-be10-22b27636156a - 86198 - LOGS_CAPTURED - Started capturing logs in process (pid: 86198).
[32m2024-09-26 09:51:59 -0500[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - f5a914fa-3413-48d5-be10-22b27636156a - 86198 - hackernews_topstories - STEP_START - Started execution of step "hackernews_topstories".
[32m2024-09-26 09:52:00 -0500[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - f5a914fa-3413-48d5-be10-22b27636156a - 86198 - hackernews_topstories - STEP_FAILURE - Execution of step "hackernews_topstories" failed.

dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "hackernews_topstories"::

KeyError: 'item_ids'

Stack Trace:
  File "/Users/eshan23/miniconda3/envs/taxi-trips-dagster/lib/python3.11/site-packages/dagster/_core/execution/plan/utils.py", line 54, in op_execution_error_boundary
    yield
  File "/Users/eshan23/miniconda3/envs/taxi-trips-dagster/lib/python3.11/site-packages/dagster/_utils/__init__.py", line 477, in iterate_with_context
    next_output = next(iterator)
                  ^^^^^^^^^^^^^^
  File "/Users/eshan23/miniconda3/envs/taxi-trips-dagster/lib/python3.11/site-packages/dagster/_core/execution/plan/compute_generator.py", line 140, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
             ^^^^^^^^^^^^^^^^^^
  File "/Users/eshan23/miniconda3/envs/taxi-trips-dagster/lib/python3.11/site-packages/dagster/_core/execution/plan/compute_generator.py", line 128, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/eshan23/eshanprashar_git_profile/taxi-trips-dagster/taxi_trips/assets/hackernews.py", line 54, in hackernews_topstories
    for item_id in hackernews_topstory_ids["item_ids"]:
                   ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
[0m
